# Generated by Django 6.0.8 on 2026-08-13 23:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "Um usuário com este IFRN-id já existe."},
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="IFRN-id",
                    ),
                ),
                (
                    "nome_registro",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="nome civil"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome social",
                    ),
                ),
                (
                    "nome_usual",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome de apresentação",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome no SUAP",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Servidor (Docente)", "Servidor (Docente)"),
                            (
                                "Servidor (Técnico-Administrativo)",
                                "Servidor (Técnico-Administrativo)",
                            ),
                            ("Prestador de Serviço", "Prestador de Serviço"),
                            ("Aluno", "Aluno"),
                            ("Desconhecido", "Desconhecido"),
                        ],
                        default="Desconhecido",
                        max_length=50,
                        null=True,
                        verbose_name="tipo de usuário",
                    ),
                ),
                (
                    "foto",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="URL da foto",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, verbose_name="CPF"),
                ),
                (
                    "rg",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="RG"),
                ),
                (
                    "passaporte",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="passaporte"),
                ),
                (
                    "data_nascimento",
                    models.DateField(blank=True, null=True, verbose_name="data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="sexo"),
                ),
                (
                    "naturalidade",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="naturalidade",
                    ),
                ),
                (
                    "campus",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="campus"),
                ),
                (
                    "first_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="primeiro login"),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="configurações"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioAuditData",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="audit_data",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
                (
                    "last_json",
                    models.JSONField(blank=True, default=dict, verbose_name="último JSON consolidado"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "dados de auditoria",
                "verbose_name_plural": "dados de auditoria",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmailUsuario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preferencial", "Preferencial"),
                            ("pessoal", "Pessoal / Secundário"),
                            ("corporativo", "Corporativo / Institucional"),
                            ("google_classroom", "Google Classroom"),
                            ("academico", "Acadêmico"),
                            ("escolar", "Escolar"),
                            ("outro", "Outro"),
                        ],
                        default="preferencial",
                        max_length=50,
                        verbose_name="tipo de e-mail",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="endereço de e-mail"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical e-mail do usuário",
                "verbose_name_plural": "historical e-mails do usuário",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSincronizacaoErro",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("endpoint", models.CharField(max_length=255, verbose_name="endpoint")),
                (
                    "status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="status HTTP"),
                ),
                ("mensagem_erro", models.TextField(verbose_name="mensagem de erro")),
                (
                    "data_ocorrencia",
                    models.DateTimeField(blank=True, editable=False, verbose_name="data da ocorrência"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical erro de sincronização",
                "verbose_name_plural": "historical erros de sincronização",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUsuario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={"unique": "Um usuário com este IFRN-id já existe."},
                        max_length=150,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="IFRN-id",
                    ),
                ),
                (
                    "nome_registro",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="nome civil"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome social",
                    ),
                ),
                (
                    "nome_usual",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome de apresentação",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="nome no SUAP",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Servidor (Docente)", "Servidor (Docente)"),
                            (
                                "Servidor (Técnico-Administrativo)",
                                "Servidor (Técnico-Administrativo)",
                            ),
                            ("Prestador de Serviço", "Prestador de Serviço"),
                            ("Aluno", "Aluno"),
                            ("Desconhecido", "Desconhecido"),
                        ],
                        default="Desconhecido",
                        max_length=50,
                        null=True,
                        verbose_name="tipo de usuário",
                    ),
                ),
                (
                    "foto",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="URL da foto",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, verbose_name="CPF"),
                ),
                (
                    "rg",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="RG"),
                ),
                (
                    "passaporte",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="passaporte"),
                ),
                (
                    "data_nascimento",
                    models.DateField(blank=True, null=True, verbose_name="data de nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="sexo"),
                ),
                (
                    "naturalidade",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="naturalidade",
                    ),
                ),
                (
                    "campus",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="campus"),
                ),
                (
                    "first_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="primeiro login"),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="configurações"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical usuário",
                "verbose_name_plural": "historical usuários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoUsuario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "suap_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="ID no SUAP"),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="identificador / matrícula",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("servidor", "Servidor"),
                            ("aluno", "Aluno"),
                            ("prestador_servico", "Prestador de Serviço"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="tipo de vínculo",
                    ),
                ),
                (
                    "campus",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="campus"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="cargo"),
                ),
                (
                    "categoria",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="categoria"),
                ),
                (
                    "curso",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="curso"),
                ),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="modalidade"),
                ),
                (
                    "nivel_ensino",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="nível de ensino",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="situação"),
                ),
                (
                    "estrangeiro",
                    models.BooleanField(default=False, verbose_name="estrangeiro"),
                ),
                (
                    "detalhamento",
                    models.JSONField(blank=True, default=dict, verbose_name="detalhamento adicional"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo",
                "verbose_name_plural": "historical vínculos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SincronizacaoErro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255, verbose_name="endpoint")),
                (
                    "status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="status HTTP"),
                ),
                ("mensagem_erro", models.TextField(verbose_name="mensagem de erro")),
                (
                    "data_ocorrencia",
                    models.DateTimeField(auto_now_add=True, verbose_name="data da ocorrência"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erros_sincronizacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "erro de sincronização",
                "verbose_name_plural": "erros de sincronização",
                "ordering": ["-data_ocorrencia"],
            },
        ),
        migrations.CreateModel(
            name="VinculoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suap_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="ID no SUAP"),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="identificador / matrícula",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("servidor", "Servidor"),
                            ("aluno", "Aluno"),
                            ("prestador_servico", "Prestador de Serviço"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="tipo de vínculo",
                    ),
                ),
                (
                    "campus",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="campus"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="cargo"),
                ),
                (
                    "categoria",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="categoria"),
                ),
                (
                    "curso",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="curso"),
                ),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="modalidade"),
                ),
                (
                    "nivel_ensino",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="nível de ensino",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="situação"),
                ),
                (
                    "estrangeiro",
                    models.BooleanField(default=False, verbose_name="estrangeiro"),
                ),
                (
                    "detalhamento",
                    models.JSONField(blank=True, default=dict, verbose_name="detalhamento adicional"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
            },
        ),
        migrations.CreateModel(
            name="EmailUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preferencial", "Preferencial"),
                            ("pessoal", "Pessoal / Secundário"),
                            ("corporativo", "Corporativo / Institucional"),
                            ("google_classroom", "Google Classroom"),
                            ("academico", "Acadêmico"),
                            ("escolar", "Escolar"),
                            ("outro", "Outro"),
                        ],
                        default="preferencial",
                        max_length=50,
                        verbose_name="tipo de e-mail",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="endereço de e-mail"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-mail do usuário",
                "verbose_name_plural": "e-mails do usuário",
                "unique_together": {("usuario", "tipo", "email")},
            },
        ),
    ]
